# NumPy

---

### 1. 개념

#### 1) 배열 (array)

- 모든 원소가 같은 자료형 [리스트와 차이]


- 원소의 개수를 바꿀 수 없음


- 적은 메모리로 데이터를 빠르게 처리할 수 있음

#### 2) 넘파이 (NumPy)

- 수치 해석용 파이썬 패키지 (벡터와 행렬을 사용하는 선형대수 계산에 사용)


- 다차원 배열 자료구조 클래스인 ndarray 클래스를 지원

In [1]:
import numpy as np

---

### 2. 1차원 배열

#### 1) 개념

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5])
print(ar)
print(type(ar))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


#### 2) 벡터화 연산 (Vectorized opreration)

In [3]:
# global하게 연산이 가능
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
2 * x # 모든 원소에 2를 곱함

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
# cf. 리스트는 *2 하면 길이가 2배로 늘어남
list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
2 * list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

---

### 3. 2차원 배열 (Matrix)

#### 1) 개념

In [5]:
# 리스트안에 리스트를 생성
m = np.array([[0, 1, 2], [3, 4, 5]])
m

array([[0, 1, 2],
       [3, 4, 5]])

#### 2) 벡터화 연산 (Vectorized opreration)

In [6]:
# global하게 연산 가능
2 * m 

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [7]:
print(len(m)) # 행 개수
print(len(m[0])) # 열 개수

2
3


---

### 4. 3차원 배열

#### 1) 개념

가장 바깥쪽리스트의 길이부터 가장 안쪽 리스트의 길의 순서로 표시

In [8]:
d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
             [[10, 11, 12, 13], [14, 15, 16, 17]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

#### 2) 벡터화 연산 (Vectorized opreration)

In [9]:
# global하게 연산 가능
3 * d

array([[[ 3,  6,  9, 12],
        [15, 18, 21, 24]],

       [[30, 33, 36, 39],
        [42, 45, 48, 51]]])

In [10]:
print(len(d)) # 행
print(len(d[0])) # 열
print(len(d[0][0])) # 깊이

2
2
4


---

### 5. 차원 / 크기 / 인덱싱 / 슬라이싱

#### 1) 차원 (Dim)

In [11]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([[2, 4, 6, 8], [1, 3, 5, 7]])
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[[2 4 6 8]
 [1 3 5 7]]


In [12]:
print(a.ndim) # 1차원 표시
print(b.ndim) # 2차원 표시

1
2


#### 2) 크기 (Shape)

In [13]:
print(a.shape) # (9, 1)
print(b.shape) # (2, 4)행렬

(9,)
(2, 4)


#### 3) 인덱싱 (Indexing)

In [14]:
print(a[2]) # 3번째 위치 (0,1,2 순)
print(b[1,2]) # (2,3)위치

3
5


#### 4) 슬라이싱 (Slicing)

In [15]:
print(b[0, :]) # 첫번째 행 정체
print(b[ : , 1]) # 두번째 열 전체

[2 4 6 8]
[4 3]


---

### 6. 배열 인덱싱 (Array indexing)

- 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 ndarray 배열을 받을 수 있음


- 인덱싱 방식엔 논리형(Boolean) 배열 방식, 정수(int) 배열 방식이 있음

#### 1) 논리형(Boolean) 배열 방식 

In [16]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 방법1
idx = np.array([True, False, True, False, True, False, True, False, True, False])
print(a[idx]) # True만 출력

# 방법2
print(a[a % 2 == 0])

[0 2 4 6 8]
[0 2 4 6 8]


#### 2) 정수(int) 배열 방식

In [17]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

---

### 연습 문제

#### `연습 문제 1`

NumPy를 사용하여 다음과 같은 행렬을 만든다.

```
10 20 30 40
50 60 70 80
```

#### `정답`

In [18]:
yeon1 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
yeon1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

#### `연습 문제 2`

다음 행렬과 같은 행렬이 있다.

```
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

#### `정답`

In [19]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [20]:
print(m[1, 2])
print(m[2, 4])
print(m[1, 1:3])
print(m[1:, 2])
print(m[0:2, 3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


#### `연습 문제3`

다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

#### `정답`

In [21]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
print(x[x % 3 == 0])
print(x[x % 4 == 1])
print(x[(x % 3 == 0) & (x % 4 ==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
