## 배열의 연산

- 벡터화 연산 (Vectorized operation)
- 스칼라와 벡터/행렬의 곱셈
- 차원 축소 연산
- 2차원 이상 연산
- 정렬

---

### 1. 벡터화 연산  (Vectorized operation)

#### 1.1 벡터화 연산

In [1]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = x + y # 벡터 + 벡터

In [2]:
z[:5]

array([10002, 10004, 10006, 10008, 10010])

#### 1.2 논리 연산 (Boolean operation)

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

print(a == b) # 각각의 원소를 비교
print(a >= b) # 각각의 원소를 비교
print(np.all(a == c)) # 모든 원소를 비교

[False  True False  True]
[False  True  True  True]
True


---

### 2. 스칼라와 벡터/행렬의 곱셈

#### 2.1 스칼라와 벡터

In [4]:
x = np.arange(10+1)
y = 10 * x

print(x) # 0부터 10까지
print(y) # x의 모든 원소에 10이 곱해짐

[ 0  1  2  3  4  5  6  7  8  9 10]
[  0  10  20  30  40  50  60  70  80  90 100]


#### 2.2 스칼라와 행렬

In [5]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = 10 * x

print(x) # (3,3) 행렬
print(y) # x 모든 행렬에 10이 곱해짐

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


#### 2.3 브로드캐스팅 (Broadcasting)

#### 2.3.1 개념

- 원래 벡터끼리나 행렬끼리 연산을 하려면 같은 크기여야 함


- 크기가 다른 사칙연산을 지원하는 것을 브로드캐스팅이라 함


- 원리는 크기가 작은 배열을 반복실행하여 크기가 큰 배열에 맞춤

#### 2.3.2 예시

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([10, 20, 30])

print(x)
print(y)
print(x+y) # y의 (10, 20, 30)이 x의 각 행에 더해짐

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30]
[[11 22 33]
 [14 25 36]
 [17 28 39]]


---

### 3. 차원 축소 연산

* 최대/최소: min, max, argmin, argmax


* 기술 통계: sum, mean, median, std, var


* 논리형 : all, any

#### 3.1 최대 / 최소

In [7]:
x = np.array([10, 20, 30, 40])

print(x.min()) # 최소값
print(x.max()) # 최댓값
print(x.argmin()) # 최소값 위치
print(x.argmax()) # 최대값 위치

10
40
0
3


#### 3.2 기술 통계

In [8]:
print(x.sum()) # 원소들의 합
print(x.mean()) # 원소들의 평균
print(np.median(x)) # 중앙값
print(x.std()) # 표준편차
print(x.var()) # 분산

100
25.0
25.0
11.180339887498949
125.0


#### 3.3 논리형

In [9]:
print(np.all([True, True, False])) # 모두 True?
print(np.any([True, True, False])) # 원소중 하나라도 True?

False
True


---

### 4. 2차원 이상 연산

- 어느 차원으로 계산할지 axis 사용


- axis = 0 인 경우는 열 연산, axis = 1인 경우는 행 연산

In [10]:
x = np.array([[1, 1], [2, 2]])
print(x)
print(x.sum(axis = 0)) # 열끼리 더함 (3, 3)
print(x.sum(axis = 1)) # 행끼리 더함 (2, 4)

[[1 1]
 [2 2]]
[3 3]
[2 4]


---

### 5. 정렬

- axis = 1 : 각각의 열을 따로 정렬 (default)


- axis = 0 : 각각의 행을 따로 정렬

In [11]:
a = np.array([[4,  3,  5,  7], [1, 12, 11,  9], [2, 15,  1, 14]])
a # 행렬 생성

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [12]:
np.sort(a) # 각 행에서 정렬

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [13]:
np.sort(a, axis = 1) # default 값과 동일 (각 행에서 정렬)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [14]:
np.sort(a, axis = 0) # 각 열에서 정렬

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [15]:
np.argsort(a) # 각 열에서 몇번째로 큰지 표시

array([[1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]])

---

### 연습문제

#### 연습 문제 1

실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

1. 전체의 최댓값
2. 각 행의 합
3. 각 열의 평균

#### 정답

In [16]:
x1 = np.arange(1, 30+1).reshape(5, 6)
x1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [17]:
print(x1.max()) # 최댓값
print(x1.sum(axis = 1)) # 각 행의 합
print(x1.mean(axis = 0)) # 각 열의 평균

30
[ 21  57  93 129 165]
[13. 14. 15. 16. 17. 18.]


#### 연습 문제 2

다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

```
array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
```

#### 정답

In [18]:
x2 = np.array([[  1,    2,    3,    4], [ 46,   99,  100,   71], [ 81,   59,   90,  100]])
x2

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [19]:
np.sort(x2, axis = 0) # 열기준

array([[  1,   2,   3,   4],
       [ 46,  59,  90,  71],
       [ 81,  99, 100, 100]])