### 선형대수 (Linear algebra)

- 데이터 분석에 필요한 각종 계산을 돕기 위한 학문
- 선형대수를 사용하면 복잡한 계산과정을 몇 글자 안되는 간단한 수식으로 서술 가능

### 1. 데이터의 유형

1) 스칼라 (scalar)

- 하나의 숫자만으로 이루어진 데이터
- 스칼라는 보통 $x$와 같이 알파벳 소문자로 표기, 실수(real number)중 하나

$$ x \in \mathbf{R} $$

2) 벡터 (vector)

- 여러 개의 숫자가 특정 순서대로 모여있는 것
- 차원(dimension) : 하나의 벡터를 이루는 데이터의 갯수
- 벡터는 복수의 행(row), 하나의 열(column)로 이루어짐
- 스칼라와 구분하기 위해 볼드체 기호($\mathbf{x}$)를 사용
- 벡터는 열의 수가 1인 행렬이기 때문에 열벡터(column vector)라고 함
- 예측문제에서 벡터는 특징벡터(feature vector)라고도 함

$$ \mathbf{x} = \begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{N} \\
\end{bmatrix}
,\;\;\;\;
x \in \mathbf{R}^{N\times1} $$

In [1]:
# 벡터 표현하기 (NumPy 사용)
# numpy import
import numpy as np

In [2]:
# 방법 1. 2차원 배열 객체로 표현
np.array([[1.1], [1.2], [1.3], [1.4]])

array([[1.1],
       [1.2],
       [1.3],
       [1.4]])

In [3]:
# 방법 2. 1차원 배열 객체로 표현
np.array([1.1, 1.2, 1.3, 1.4]) # 1X4 처럼 보이지만 실제는 4X1 벡터

array([1.1, 1.2, 1.3, 1.4])

3) 행렬 (Matrix)

(1) 정의

- 복수의 차원을 가지는 데이터 레코드가 다시 여러개 있는 경우를 합쳐서 표기
- N(행) x M(열) 형태로 나타남
- 알파벳 대문자로 주로 표기 ($X$)

$$ \mathbf{x} = \begin{bmatrix}
x_{1,1} & x_{1,2} & \cdots & x_{1,M}\\
x_{2,1} & x_{2,2} & \cdots & x_{2,M}\\
\vdots & \vdots & \ddots & \vdots\\
x_{N,1} & x_{N,2} & \cdots & x_{N,M}\\
\end{bmatrix},\;\;\;\;
\mathbf{x} \in \mathbf{R}^{N \times M} $$ 

- 하나의 레코드를 단독으로 벡터로 나타낼 때는 하나의 열(column)로 나타남
- 복수의 데이터 레코드 집합을 행렬로 나타낼 때는 하나의 데이터 레코드가 하나의 행(row)로 표시

In [4]:
# 행렬 표현하기
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(2) 표기법

* 복수의 열 벡터 $c_i$, 또는 복수의 행 벡터 $r_j^T$ 을 합친(concatenated) 형태로 표기

$$
X 
=
\left[
\begin{array}{c|c|c|c}
& & & \\
c_1 &  c_2 & \cdots & c_M \\
& & & \\
\end{array}
\right]
=
\begin{bmatrix}
\;\;\;\;\; r_1^T \;\;\;\;\; \\ \hline
r_2^T \\ \hline
\vdots \\ \hline
r_N^T \\  
\end{bmatrix}
$$

   행 관점
   - 행렬 $X$의 각 열은 $c_1$, $c_2$, $\ldots$, $c_M$라고 이름 붙임
   - 행렬 $X$는 열 벡터 $c_1$, $c_2$, $\ldots$, $c_M$으로 이루어짐

   열 관점
   - 행렬 $X$의 각 행은 $r_1^T$, $r_2^T$, $\ldots$, $r_N^T$라고 이름 붙임
   - 행렬 $X$는 행 벡터 $r_1^T$, $r_2^T$, $\ldots$, $r_N^T$으로 이루어짐

* 행렬  $$ X \in \mathbf{R}^{N\times M}$$

* 열 벡터 $$c_i \in \mathbf{R}^{N \times 1} \; (i=1,\cdots,M)$$

* 행 벡터 $$r_j^T \in \mathbf{R}^{1 \times M} \; (j=1,\cdots,N) $$

### 2. 전치 연산 (Transpose)

- 행과 열을 바꾸는 연산
- 벡터나 행렬에 $T$라는 위첨자(super-script)를 붙여서 표기

1) 벡터

$$x = 
\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{N} \\
\end{bmatrix}
\; ,\;\;\;\;
x^T = 
\begin{bmatrix}
x_{1} & x_{2} & \cdots & x_{N}
\end{bmatrix} $$

2) 행렬

$$ \mathbf{x} =\begin{bmatrix}
x_{1,1} & x_{1,2} & \cdots & x_{1,M}\\
x_{2,1} & x_{2,2} & \cdots & x_{2,M}\\
\vdots & \vdots & \ddots & \vdots\\
x_{N,1} & x_{N,2} & \cdots & x_{N,M}\\
\end{bmatrix}
\; ,\;\;\;\;
\mathbf{x^T} =
\begin{bmatrix}
x_{1,1} & x_{2,1} & \cdots & x_{N,1}\\
x_{1,2} & x_{2,2} & \cdots & x_{N,2}\\
\vdots & \vdots & \ddots & \vdots\\
x_{1,M} & x_{2,M} & \cdots & x_{M,N}\\
\end{bmatrix} $$

In [5]:
# 전치 연산하기(벡터) - 1차원은 적용 X
np.array([[1.1], [1.2], [1.3], [1.4]]).T

array([[1.1, 1.2, 1.3, 1.4]])

In [6]:
# 전치 연산하기(행렬)
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### 3. 특수한 벡터와 행렬

1) 영 벡터 : 모든 원소가 0인 N차원 벡터

$$ \mathbf{0}_N = \mathbf{0} = 0 =
\begin{bmatrix}
0 \\
0 \\
\vdots \\
0 \\
\end{bmatrix}
$$

$$ 0 \in \mathbf{R}^{N \times 1} $$

In [7]:
# 영 벡터 표현하기
np.zeros(3)

array([0., 0., 0.])

In [8]:
# 영 행렬 표현하기
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2) 일 벡터 : 모든 원소가 1인 N차원 벡터

$$ \mathbf{1}_N = \mathbf{1}  = 1 = 
\begin{bmatrix}
1 \\
1 \\
\vdots \\
1 \\
\end{bmatrix}
$$

$$ 1 \in \mathbf{R}^{N \times 1} $$

In [9]:
# 일 벡터 표현하기
np.ones(3)

array([1., 1., 1.])

In [10]:
# 일 행렬 표현하기
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3) 정방 행렬(Square matrix) : 행의 갯수와 열의 갯수가 같은 행렬 (정사각형꼴)

$$ \mathbf{x} =\begin{bmatrix}
x_{1,1} & x_{1,2} & \cdots & x_{1,N}\\
x_{2,1} & x_{2,2} & \cdots & x_{2,N}\\
\vdots & \vdots & \ddots & \vdots\\
x_{N,1} & x_{N,2} & \cdots & x_{N,N}\\
\end{bmatrix} $$

In [11]:
# 정방 행렬 표현하기
np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

4) 대각 행렬(diagonal matrix) : 모든 비대각 요소가 0인 정방 행렬

- 대각(diagonal) : 행과 열이 같은 위치 (대각선 방향)
- 비대각(off-diagonal) : 대각 위치에 않은 모든 것들

$$ 
D = 
\begin{bmatrix}
D_{1} & 0 & \cdots & 0 \\
0 & D_{2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & D_{N} \\
\end{bmatrix}
$$

In [12]:
# 대각 행렬 표현하기
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

5) 단위 행렬(identity matrix) : 대각 행렬 중 모든 대각 성분 값이 1인 대각 행렬

$$ 
I = 
\begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1 \\
\end{bmatrix}
$$

In [13]:
# 단위 행렬 표현하기
# 방법 1. identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# 방법 2. eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

6) 대칭 행렬(Symmetric matrix) : 전치 행렬과 원래의 행렬이 같은 행렬

$$ S^{T} = S $$ 



In [15]:
# 대칭 행렬 표현하기
np.array([[1, 2, 3], [2, 5, 4], [3, 4, 7]])

array([[1, 2, 3],
       [2, 5, 4],
       [3, 4, 7]])

### 연습문제

#### ``연습 문제 1``

NumPy를 사용해서 다음에 제시한 붓꽃 데이터 $x_2$에 대한 벡터 변수 ``x1``를 만든다.

$$  x_1 = 
\begin{bmatrix}
4.9 \\
3.0 \\
1.4 \\
0.2 \\
\end{bmatrix}
$$

In [16]:
x1 = np.array([[4.9], [3.0], [1.4], [0.2]])
x1

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

#### ``연습 문제 2``

NumPy를 사용해서 다음에 제시한 붓꽃 데이터 $X$에 대한 행렬 변수 ``X2``를 만든다.

$$ 
X2=
\begin{bmatrix}
5.1 & 3.5 & 1.4 & 0.2 \\
4.9 & 3.0 & 1.4 & 0.2 \\
\end{bmatrix}
$$

In [17]:
X2 = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
X2

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

#### ``연습 문제 3``

1) NumPy를 사용해서 다음에 제시한 붓꽃 데이터 $X3$의 전치행렬 $X3^T$을 구한다.

$$ 
X3=
\begin{bmatrix}
5.1 & 3.5 & 1.4 & 0.2 \\
4.9 & 3.0 & 1.4 & 0.2 \\
\end{bmatrix}
$$

2) 전치행렬을 다시 전치한 행렬 $(X3^T)^T$을 구한다. 이 행렬과 원래 행렬 $X3$을 비교한다.

In [18]:
# 연습문제 3-1
X3 = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
X3.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [19]:
print(X3.T.T)
print(X3)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]


#### ``연습 문제 4``

1. 영 벡터, 일 벡터, 정방 행렬, 대각 행렬, 단위 행렬, 대칭 행렬의 예를 하나씩 만들어 본다.
2. 위의 벡터와 행렬을 NumPy로 나타내 본다.

In [20]:
# 3. 특수한 백터와 행렬 참고